### ISSUE TITLE
Dev run instructions

### ISSUE THREAD

**Issue by fulldecent** [mcandre/lili#16]
Please include instructions for compiling and running.

I am doing:

    gem install bundler
    bundle install
    ./bin/lili

and get:

```
williamentriken@Williams-iMac ~/D/lili> ./bin/lili
/usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- lili (LoadError)
	from /usr/local/Cellar/ruby/2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./bin/lili:8:in `<main>'
```

**Comment by mcandre** [comment]
Try `lili` or `bundle exec lili`

**Comment by fulldecent** [comment]
Great, thank you
