### ISSUE TITLE
Clarify how to run cucumber tests

### ISSUE THREAD

**Issue by fulldecent** [mcandre/lili#17]
The README says to run

    $ cucumber

But this produces:

````
williamentriken@Williams-iMac ~/D/gtdlint> cucumber 
Feature: Run example tests

  Scenario: Running example tests            # features/run_example_tests.feature:3
    Given the program has finished           # features/step_definitions/steps.rb:1
      No such file or directory - gtdlint (Errno::ENOENT)
      ./features/step_definitions/steps.rb:3:in ``'
      ./features/step_definitions/steps.rb:3:in `/^the program has finished$/'
      features/run_example_tests.feature:4:in `Given the program has finished'
    Then the output is correct for each test # features/step_definitions/steps.rb:10

Failing Scenarios:
cucumber features/run_example_tests.feature:3 # Scenario: Running example tests

1 scenario (1 failed)
2 steps (1 failed, 1 skipped)
0m0.025s
````

**Comment by mcandre** [comment]
Maybe you're missing the dependencies? Try `bundle install; cucumber`

**Comment by fulldecent** [comment]
Thank you, this worked:

    bundle install
    bundle exec cucumber
